import type { Agency, DemoState, Zone } from "./types";
export const zones: Zone[] = [
  {
    id: "Z-01",
    name: "River corridor",
    district: "Kamrup Metropolitan",
    center: [91.721, 26.188],
    risk: 82,
    hazard: "flood",
    sensors: 4,
  },
  {
    id: "Z-02",
    name: "Eastern catchment",
    district: "Kamrup Metropolitan",
    center: [91.814, 26.177],
    risk: 63,
    hazard: "flood",
    sensors: 3,
  },
  {
    id: "Z-03",
    name: "Southern uplands",
    district: "Kamrup Metropolitan",
    center: [91.767, 26.122],
    risk: 31,
    hazard: "forest-fire",
    sensors: 2,
  },
  {
    id: "Z-04",
    name: "Western sector",
    district: "Kamrup",
    center: [91.621, 26.145],
    risk: null,
    hazard: "heat-wave",
    sensors: 0,
  },
];
export const agencies: Agency[] = [
  {
    id: "A-01",
    name: "River Rescue Unit",
    verified: true,
    capabilities: ["Flood", "Evacuation", "Trapped"],
  },
  {
    id: "A-02",
    name: "Regional Response Unit",
    verified: true,
    capabilities: [
      "Medical",
      "Fire",
      "Infrastructure danger",
      "Missing person",
      "Other",
    ],
  },
  {
    id: "A-03",
    name: "Community Support Group",
    verified: false,
    capabilities: ["Evacuation"],
  },
];
const now = () => new Date().toISOString();
export function initialState(): DemoState {
  return {
    incidents: [
      {
        id: "RG-1042",
        category: "Flood",
        people: 4,
        description:
          "Water entering the ground floor. Family waiting upstairs.",
        zoneId: "Z-01",
        landmark: "Demo location · Riverside lane",
        status: "New",
        priority: "Critical",
        ownerId: "demo-citizen",
        agencyId: null,
        teamId: null,
        createdAt: now(),
        version: 1,
        timeline: [{ time: now(), action: "Demo SOS received" }],
      },
      {
        id: "RG-1041",
        category: "Medical",
        people: 1,
        description: "Medical assistance requested at a demo shelter.",
        zoneId: "Z-02",
        landmark: "Demo location · Community hall",
        status: "Acknowledged",
        priority: "High",
        ownerId: "demo-other",
        agencyId: "A-02",
        teamId: null,
        createdAt: now(),
        version: 2,
        timeline: [
          { time: now(), action: "Acknowledged by Regional Response Unit" },
        ],
      },
      {
        id: "RG-1040",
        category: "Evacuation",
        people: 8,
        description: "Assistance moving residents from a low-lying area.",
        zoneId: "Z-01",
        landmark: "Demo location · North embankment",
        status: "Assigned",
        priority: "High",
        ownerId: "demo-other",
        agencyId: "A-01",
        teamId: "R-01",
        createdAt: now(),
        version: 3,
        timeline: [{ time: now(), action: "River Team Alpha assigned" }],
      },
      {
        id: "RG-1039",
        category: "Trapped",
        people: 2,
        description: "Residents awaiting assistance from a demo response team.",
        zoneId: "Z-02",
        landmark: "Demo location · East access road",
        status: "On scene",
        priority: "Critical",
        ownerId: "demo-other",
        agencyId: "A-01",
        teamId: "R-02",
        createdAt: now(),
        version: 5,
        timeline: [{ time: now(), action: "Team reached the demo location" }],
      },
      {
        id: "RG-1038",
        category: "Infrastructure danger",
        people: 0,
        description: "Road damage recorded for assessment.",
        zoneId: "Z-03",
        landmark: "Demo location · Southern road",
        status: "Resolved",
        priority: "Moderate",
        ownerId: "demo-other",
        agencyId: "A-02",
        teamId: null,
        createdAt: now(),
        version: 6,
        timeline: [{ time: now(), action: "Demo incident resolved" }],
      },
    ],
    resources: [
      {
        id: "R-01",
        name: "River Team Alpha",
        agencyId: "A-01",
        type: "Rescue team",
        capacity: 6,
        status: "Assigned",
        incidentId: "RG-1040",
      },
      {
        id: "R-02",
        name: "River Team Bravo",
        agencyId: "A-01",
        type: "Rescue team",
        capacity: 5,
        status: "Assigned",
        incidentId: "RG-1039",
      },
      {
        id: "R-03",
        name: "River Team Charlie",
        agencyId: "A-01",
        type: "Rescue team",
        capacity: 6,
        status: "Available",
      },
      {
        id: "R-04",
        name: "Response Team Delta",
        agencyId: "A-02",
        type: "Rescue team",
        capacity: 4,
        status: "Available",
      },
      {
        id: "R-05",
        name: "Rescue Boat 01",
        agencyId: "A-01",
        type: "Boat",
        capacity: 8,
        status: "Available",
      },
      {
        id: "R-06",
        name: "Medical Vehicle 01",
        agencyId: "A-02",
        type: "Vehicle",
        capacity: 2,
        status: "Available",
      },
      {
        id: "R-07",
        name: "Response Vehicle 02",
        agencyId: "A-02",
        type: "Vehicle",
        capacity: 4,
        status: "Maintenance",
      },
    ],
    warnings: [
      {
        id: "W-01",
        zoneId: "Z-01",
        hazard: "flood",
        title: "Rising water in the river corridor",
        instructions:
          "Demo preparedness notice: avoid low-lying river access. Review the listed shelter information and follow authorized local guidance.",
        severity: "High",
        status: "Published",
        createdAt: now(),
        expiresAt: new Date(Date.now() + 86400000).toISOString(),
      },
      {
        id: "W-02",
        zoneId: "Z-02",
        hazard: "flood",
        title: "Eastern catchment requires monitoring",
        instructions:
          "Review local conditions and prepare available response resources. This is a simulated notice.",
        severity: "Moderate",
        status: "Draft",
        createdAt: now(),
        expiresAt: new Date(Date.now() + 86400000).toISOString(),
      },
    ],
    messages: [],
    assessments: [
      {
        id: "AS-01",
        zoneId: "Z-01",
        finding:
          "Illustrative water exposure affecting a road and 12 example structures.",
        needs:
          "Temporary shelter, clean water and an infrastructure inspection.",
        state: "Reviewed",
      },
    ],
    coordination: [],
    agencies: structuredClone(agencies),
    scenario: "rising",
    sample: 4,
    rules: { persistence: 3, minimumSupport: 2, highThreshold: 70 },
    audit: [
      { id: "AU-01", time: now(), action: "Demo environment initialized" },
    ],
  };
}
export const shelters = [
  {
    id: "S-01",
    name: "Community Hall Shelter",
    zoneId: "Z-02",
    capacity: 120,
    occupied: 46,
    accessible: true,
    center: [91.797, 26.172] as [number, number],
  },
  {
    id: "S-02",
    name: "Southern Relief Centre",
    zoneId: "Z-03",
    capacity: 80,
    occupied: 23,
    accessible: true,
    center: [91.757, 26.127] as [number, number],
  },
  {
    id: "S-03",
    name: "Western Assembly Point",
    zoneId: "Z-04",
    capacity: 60,
    occupied: 0,
    accessible: false,
    center: [91.653, 26.149] as [number, number],
  },
];
